version: '3.4'

services:
  socialmediaapi:
    image: socialmediaapi
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
