version: '3.4'

services:
  # socialmediaapi:
  #   image: socialmediaapi
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     # Only will build development stage from our dockerfile
  #     target: development
  #   # Mount our host Directory to the docker container
  #   # Mount (.) current directory to the docker container usr/src/app
  #   # reflect file changes from host to container
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #   - .env
  #    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
  #   # Run in dev Mode: npm run start:dev
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes:
  postgres-data:
    